config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, expect: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end

  devise_for :users, skip: :registrations
  root to: 'static#homepage'
end

app/views/shared/_admin_dropdown.html.erb
<li>
  <%= link_to "Admin Dashboard", admin_root_path %>
</li>
<li class="divider">
</li>

app/views/shared/_alerts.html.erb
<% if flash[:alert] %>
  <%= js add_gritter(flash[:alert], title: "OvertimeApp Notification", sticky: false, time: 3000) %>
<% elsif flash[:error] %>
  <%= js add_gritter(flash[:error], title: "OvertimeApp Notification", sticky: false, time: 3000) %>
<% else %>
  <%= js add_gritter(flash[:notice], title: "OvertimeApp Notification", sticky: false, time: 3000) %>
<% end %>

app/views/shared/_audit_log_tab.html.erb
<li class="<%= active?(audit_logs_path) %>">
  <%= link_to "Audit Log", audit_logs_path  %>
</li>

app/views/shared/_employee_nav_items.html.erb
<li class="<%= active?(posts_path) %>">
  <%= link_to "Enteries", posts_path  %>
</li>

<li class="<%= active?(new_post_path) %>">
  <%= link_to "Submit Hours", new_post_path, id: "new_post_from_nav"  %>
</li>

app/views/shared/_form.html.erb
<%= simple_form_for @post do |f| %>
    <%= f.input :date, as: :string, input_html: { value: Date.today.strftime("%d/%m/%Y") }  %>
    <%= f.input :work_performed, as: :text %>
    <%= f.input :daily_hours %>
    <%= render 'shared/status', f: f if current_user.type == "AdminUser" %>
    <%= f.button :submit, "Save", class: 'btn-primary' %>
  <% end %>

app/views/shared/_navbar.html.erb
<div class="logo">
  <h1> Time Tracker </h1>
</div>

<% if current_user %>
  <ul class="custom-nav nav nav-tabs">
    <li class="<%= active?(root_path) %>">
      <%= link_to "", root_path, class: "glyphicon glyphicon-home" %>
    </li>

    <%= render 'shared/employee_nav_items' if employee? %>

    <%= render 'shared/audit_log_tab' if admin? %>


    <li class="dropdown pull-right">
       <a href="#" data-toggle="dropdown" class="dropdown-toggle">Options<strong class="caret"></strong></a>
      <ul class="dropdown-menu">

        <%= render 'shared/admin_dropdown' if admin? %>

        <li>
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        </li>
      </ul>
    </li>
  </ul>
<% end %>

app/views/shared/_status.html.erb
<%= f.input :status, as: :radio_buttons, collection: Post.statuses.keys %>