config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, expect: [:new, :edit, :destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users
    resources :employees

    root to: "users#index"
  end

  resources :posts do
    member do
      get :approve
    end
  end

  devise_for :users, skip: :registrations
  root to: 'static#homepage'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :work_performed, :date, :daily_hours, presence: true
  validates :daily_hours, numericality: { greater_than: 0.0 }
  enum status: { submitted: 0, approved: 1, rejected: 2 }

  scope :posts_by, ->(user) { where(user: user) }

  after_save :confirm_audit_log, if: :submitted?
  after_save :un_confirm_audit_log, if: :rejected?

  private
    def un_confirm_audit_log
      audit_log = AuditLog.where(user: self.user, start_date: (self.date - 7.days..self.date)).last
      audit_log&.pending!
    end

    def confirm_audit_log
      audit_log = AuditLog.where(user: self.user, start_date: (self.date - 7.days..self.date)).last
      audit_log&.confirmed!
    end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # you can overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.
    #     page(params[:page]).
    #     per(10)
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :destroy, :update, :approve]
  def index
    @posts = Post.posts_by(current_user).page(params[:page]).per(10)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to @post, notice: "Your post was created"
    else
      render :new
    end
  end

  def show

  end

  def edit
    authorize @post
  end

  def update
    authorize @post
    if @post.update(post_params)
      redirect_to post_path(@post), notice: "Your post was update"
    else
      render :edit
    end
  end

  def destroy
    @post.delete
    redirect_to posts_path,  notice: "Your post was deleted"
  end

  def approve
    authorize @post
    @post.approved!
    redirect_to root_path, notice: "The post was approved"
  end

  private
  def post_params
    params.require(:post).permit(:date, :work_performed, :status, :daily_hours)
  end

  def set_post
    @post = Post.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_post.html.erb
<tr>
  <td>
    <%= post.daily_hours.to_f %>
  </td>
  <td>
    <%= post.date.strftime("%m/%d/%Y")  %>
  </td>
  <td class="hidden-xs">
    <%= link_to truncate(post.work_performed), post_path(post) %>
  </td>
  <td>
   <%= status_label(post.status.capitalize) %>
  </td>
  <td>
    <%= link_to '', edit_post_path(post), class: 'glyphicon glyphicon-pencil index-icons', id: "edit_#{post.id}" if policy(post).update? %>
  </td>
  <td>
    <%= link_to "", post_path(post), method: :delete, class: "glyphicon glyphicon-trash index-icons", id: "delete_post_#{post.id}_from_index", data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/posts/edit.html.erb
<div class="container">
  <h2>Edit the post </h2>
  <%= render 'shared/form' %>
</div>

<% content_for(:js) do  %>
  <script > 
        $('#post_date').datepicker({
            uiLibrary: 'bootstrap4',
            format: "dd/mm/yyyy"
        });
  </script>

<% end %>

app/views/posts/index.html.erb
<h1>Posts</h1>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <table class="table table-hover table-striped">
        <thead>
          <tr>
            <th>
              Hours
            </th>
            <th>
              Date
            </th>
            <th class="hidden-xs">
              Work Performed
            </th>
            <th>
              Status
            </th>
            <th>

            </th>
            <th>

            </th>
          </tr>
        </thead>
        <tbody id='posts'>
          <%= render @posts %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<div id="paginator">
  <%= paginate @posts, remote: true %>
</div>

app/views/posts/index.js.erb
$('#posts').html('<%= escape_javascript render(@posts) %>');
$('#paginator').html('<%= escape_javascript(paginate(@posts, remote: true).to_s) %>');

app/views/posts/new.html.erb
<div class="container">
  <h2>Create new post </h2>
  <%= render "shared/form" %>
</div>

<% content_for(:js) do  %>
  <script > 
        $('#post_date').datepicker({
            uiLibrary: 'bootstrap4',
            format: "dd/mm/yyyy"
        });
  </script>

<% end %>

app/views/posts/show.html.erb
<div>
  <h2> <%= @post.work_performed %> </h2>
</div>

<div class="well">
  <div>
    <h3> <span>Hours worked: </span> <%= @post.daily_hours %> </h3>
  </div>

  <div>
    <h3> <span>User: </span> <%= @post.user.full_name %> </h3>
  </div>

  <div>
    <h3> <span>Date: </span> <%= @post.date %> </h3>
  </div>

  <div>
    <h3> <span>Current stage of Approval: </span> <%= @post.status.capitalize %> </h3>
  </div>
</div>

<%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" if policy(@post).update? %>